blank_issues_enabled: false
contact_links:
- name: ğŸ“ Code of Conduct
  url: https://github.com/marmelab/gremlins.js/blob/master/CODE_OF_CONDUCT.md
  about: â¤ Be nice to other members of the community. â˜® Behave.
